services:
  open-webui:
    image: ${DOCKER_REGISTRY:-open-webui}/open-webui:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME:-open-webui}
    volumes:
      - ${DATA_DIR:-/app/backend/data}:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080

volumes:
  open-webui: {}
